# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Stop docker
        run: |
          docker stop $(docker ps | grep ":5000" | awk '{print $1}')

      - name: build and run docker file
        run: |
          docker build -t ghcr.io/vanloocklennert/imdb-api:latest ./API
          docker run -d -p 5000:80 ghcr.io/vanloocklennert/imdb-api:latest
      
      #- name: Test Docker container
      # run: |
      #    curl localhost:5000
      
      - name: 'Set up python'
        run: |
          sudo apt install python3
      
      - name: "install requirements"
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: "Azure login"  
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Run data prep script
        working-directory: model/scripts
        run: |
          python3 preprocessing.py

      - name: Run training script
        working-directory: model/scripts
        run: |
          python3 training.py